# Generated by Django 4.2.3 on 2023-07-19 22:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(db_index=True, max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('phone_number', models.CharField(default='+1-234-567-89-01', max_length=16, verbose_name='Телефон')),
                ('add_text', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Форму обратной связи',
                'verbose_name_plural': 'Форма обратной связи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramEdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=40, verbose_name='URL')),
                ('min_age', models.PositiveIntegerField(default=0, verbose_name='Минимальный возраст')),
                ('max_age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(1)], verbose_name='Максимальный возраст')),
                ('about', models.TextField(blank=True, verbose_name='О программе')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото программы')),
                ('price', models.IntegerField(blank=True, verbose_name='Стоимость обучения')),
            ],
            options={
                'verbose_name': 'Программу',
                'verbose_name_plural': 'Программы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WED', 'Среда'), ('THU', 'Четверг'), ('FRI', 'Пятница'), ('SAT', 'Суббота'), ('SUN', 'Воскресенье')], default='MON', max_length=3, verbose_name='День недели')),
                ('start_edu', models.TimeField(verbose_name='Начало урока')),
                ('finish_edu', models.TimeField(verbose_name='Конец урока')),
                ('name_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kidsedu.programedu', verbose_name='ID программы')),
            ],
            options={
                'verbose_name': 'Расписание занятий',
                'verbose_name_plural': 'Расписание занятий',
                'ordering': ['id'],
            },
        ),
    ]
