# Generated by Django 4.2.3 on 2023-07-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsedu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programedu',
            name='name',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='programedu',
            name='slug',
            field=models.SlugField(max_length=40, unique=True, verbose_name='URL'),
        ),
    ]
