# Generated by Django 4.2.3 on 2023-07-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsedu', '0002_alter_programedu_name_alter_programedu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleedu',
            name='week_day',
            field=models.CharField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], default='1', max_length=3, verbose_name='День недели'),
        ),
    ]
