# Generated by Django 4.2.3 on 2023-08-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsedu', '0003_alter_scheduleedu_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personform',
            name='phone_number',
            field=models.CharField(max_length=16, null=True, verbose_name='Телефон'),
        ),
    ]
