# Generated by Django 4.2.3 on 2023-08-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsedu', '0004_alter_personform_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personform',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, verbose_name='Телефон'),
        ),
    ]
