# Generated by Django 4.2.3 on 2023-08-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsedu', '0005_alter_personform_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personform',
            options={'ordering': ['id'], 'verbose_name': 'Форма обратной связи', 'verbose_name_plural': 'Форма обратной связи'},
        ),
        migrations.AlterField(
            model_name='personform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='personform',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='Телефон'),
        ),
    ]
